baseURL: "https://fighthaven.club/"
languageCode: "en-us"
title: "Fighthaven"
theme: "hello-friend-ng"
summaryLength: 60
paginate: 10

# Just a quick description used by some themes
params:
  description: "The Bay Area Rationalist Fight Club"
  homeSubtitle: "The Bay Area Rationalist Fight Club"
  # Hello Friend NG-specific params
  dateFormat: "02 Jan 2006"

# Generate HTML and RSS for the events section
outputs:
  section:
    - HTML
    - RSS

# Media type and output format definitions for custom RSS feed
mediaTypes:
  application/rss+xml:
    suffixes: ["xml"]

outputFormats:
  RSS:
    mediaType: "application/rss+xml"
    baseName: "index"

# Menu example (if you want top nav items)
menu:
  main:
    - identifier: "events"
      name: "Events"
      url: "/events/"
    - identifier: "discord"
      name: "Discord"
      url: "https://discord.gg/fighthaven"
      params:
        newTab: true
